README.md, src/cli.js, src/index.js
Realized I should be using path.resolve, not path.join, since it won't support absolute paths. Also the output was kind of ugly for custom scenarios. And I realized the docs were wrong for `createTests`.
=> fix: use path.resolve(), tidy output, add docs

README.md, src/cli.js, test/spec/cli.mjs, test/spec/util.js
Fixes #12
Adds a new flag, `--setup`, that is used to override the scenario's `setup` function. This should hopefully address the very common use case of "I want to use the default scenario, but I want to log in with a username/password first."
=> feat: add --setup flag

src/analyzeDomNodes.js, test/spec/domNodes.test.mjs, test/spec/eventListeners.test.mjs, test/www/recyclesDomNodesNewIds/index.html, test/www/recyclesDomNodesNewIdsAndActualLeak/index.html, test/www/recyclesEventListeners/index.html, test/www/recyclesEventListenersNewNodeIds/index.html
If a DOM node is constantly being recycled, but with a different ID every time, then we can detect a "leak" that doesn't exist. This fixes that.
=> fix: better handle changing dom node descriptions

src/analyzeDomNodes.js, src/format.js, src/index.js, test/spec/domNodes.test.mjs, test/spec/eventListeners.test.mjs, test/www/domNodesLeakWithNewNames/index.html, test/www/listenersLeakWithNewNames/index.html
In situations where event listeners or DOM nodes are leaking, but the unique identifiers for those objects (i.e. the names/ids/classes/etc) are constantly changing, the tool doesn't do a great job of summarizing the breakdown. But we should at least print out that a leak is detected.
=> fix: handle changing event/node names

.github/workflows/tests.yml, package.json
We should probably test on node 14 since that's our min supported Node version.
=> fix: update minimum node version, test in 14

README.md, src/cli.js, src/index.js
Fixes #39
Unfortunately there isn't a great way to test this, so I'm just adding the feature with no test.
I was going to try a page with CSP and use `--disable-web-security`, but that option seems to have been removed from Chromium. Goes to show how unstable these options are, so there isn't a "well-supported" one that we can reasonably test.
=> feat: add --browser-arg option

package.json, src/resolveSourceMappedPositions.js, src/thirdparty/source-map-resolve/LICENSE, src/thirdparty/source-map-resolve/source-map-resolve.js, yarn.lock
`source-map-resolve` is deprecated, but I've yet to find a better replacement, so let's just vendor it for now and remove the parts I'm not using.
=> fix: remove source-map-resolve

README.md, scenario.mjs, src/index.js, test/spec/customScenario.test.mjs, types/index.d.ts
In JupyterLab, some scenarios involves creating some assets on the server before running the monitored code. It will be good to be able to remove those assets to have real identical iterations.
So this PR adds an optional teardown function to scenario.
=> Add optional teardown to scenario

.github/workflows/tests.yml
`--immutable` is yarn v2, we're using yarn v1.
=> chore: use yarn --frozen-lockfile in CI

package.json, src/metrics/heapsnapshots/analyzeHeapsnapshots.js, yarn.lock
Updating puppeteer requires us to ignore another internal V8 class, kind of strange this only pops up with the puppeteer update (not a Chromium update), but seems like not a big deal.
=> fix: update puppeteer

src/index.js, test/spec/basic.test.mjs
If you run with `--heapsnapshot`, it prints `(undefined iterations)`. This fixes that.
=> fix: result should have numIterations

src/metrics/collections/collections.js, test/spec/collections.test.mjs, test/www/collectionsWithLotsOfLeaks/index.html, test/www/collectionsWithLotsOfLeaks/script.js
Fixes #89.
Turns out we can have an OOM with a small number of collections, if they leak several times. (E.g. an array leaking 2000 items every iteration, with a separate `push()` call for each leak.)
=> fix: fix OOM when collections leak multiple times

package.json, test/spec/errors.test.mjs, yarn.lock
Fixes #92
We can unpin it when Chromium 122 is released; that fixes the Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1522685
=> fix: pin puppeteer for now

src/defaultScenario.js, test/www/invisibleLinks/index.html
This is just something annoying I've noticed on a particular site. It uses `visibility: hidden` for some anchor elements. We should detect that.
=> fix: check for element visibility in defaultScenario

src/index.js
It's annoying when you're trying to debug and it times out. This effectively disables the `protocolTimeout` in debug mode.
=> fix: increase protocolTimeout in debug mode

package.json, pnpm-lock.yaml, src/metrics/domNodesAndListeners/eventListeners.js
I realized we can just get rid of `uuid` entirely; the `crypto` API is available in all our supported Node versions, and apparently [it's faster](https://dev.to/galkin/crypto-randomuuid-vs-uuid-v4-47i5).
=> fix: use built-in crypto.randomUUID

.mocharc.json, package.json, pnpm-lock.yaml, test/spec/basic.test.js, test/spec/cli.test.js, test/spec/collections.test.js, test/spec/customIdleLogic.test.js, test/spec/customScenario.test.js, test/spec/domNodes.test.js, test/spec/errors.test.js, test/spec/eventListeners.test.js, test/spec/heapsnapshots.test.js, test/spec/invalidCollection.test.js, test/spec/promisePool.test.js, test/spec/setup.mjs, test/spec/shadowDom.test.js
We can use `node --test` now; it's good enough for our use case.
=> chore: remove mocha, use built-in test runner

src/index.js, src/metrics/collections/collections.js
There are excessive debugger statements here when you're trying to debug leaking collections.
I also added some comments to clarify what you should do if you're paused on one of these statements.
=> fix: improve `debugger` statements in `--debug` mode

package.json, pnpm-lock.yaml
BREAKING CHANGE: Puppeteer's env vars have changed, see https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-v23.0.0
=> fix: update puppeteer and pnpm

package.json, pnpm-lock.yaml, pnpm-workspace.yaml, test/spec/errors.test.js
Forked from #125
Updating dependencies without `devtools-frontend` because it's proving to be more trouble than expected
=> fix: update dependencies
